"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Watermelon_1 = require("./Watermelon");
var Firemelon_1 = require("./Firemelon");
var Earthmelon_1 = require("./Earthmelon");
var Airmelon_1 = require("./Airmelon");
var Melolemonmelon_1 = require("./Melolemonmelon");
var watermelon = new Watermelon_1.Watermelon(12.5, "Kingsize");
var firemelon = new Firemelon_1.Firemelon(2, "firemelon");
var earthmelon = new Earthmelon_1.Earthmelon(3, "earthmelon");
var airmelon = new Airmelon_1.Airmelon(4, "airmelon");
var melolemonmelon = new Melolemonmelon_1.Melolemonmelon(13, "Kingsize");
console.log(watermelon.toString());
console.log('_______________________________________________________');
console.log(firemelon.toString());
console.log('_______________________________________________________');
console.log(earthmelon.toString());
console.log('_______________________________________________________');
console.log(airmelon.toString());
console.log('_______________________________________________________');
console.log(melolemonmelon.toString());
melolemonmelon.morph();
console.log('_______________________________________________________');
console.log(melolemonmelon.toString());
melolemonmelon.morph();
console.log('_______________________________________________________');
console.log(melolemonmelon.toString());
melolemonmelon.morph();
console.log('_______________________________________________________');
console.log(melolemonmelon.toString());
melolemonmelon.morph();
console.log('_______________________________________________________');
console.log(melolemonmelon.toString());
melolemonmelon.morph();
console.log('_______________________________________________________');
console.log(melolemonmelon.toString());
melolemonmelon.morph();
console.log('_______________________________________________________');
console.log(melolemonmelon.toString());
melolemonmelon.morph();
console.log('_______________________________________________________');
console.log(melolemonmelon.toString());
melolemonmelon.morph();
